# Generated by Django 5.2.1 on 2025-06-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги/игры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('vk_link', models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на VK для записи/подробностей')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Услуга/Игра',
                'verbose_name_plural': 'Услуги и Игры',
                'ordering': ['order'],
            },
        ),
    ]
