# Generated by Django 5.2.1 on 2025-06-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Услуга или Игра', 'verbose_name_plural': 'Услуги и Игры'},
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vk_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на VK'),
        ),
    ]