# Generated by Django 5.2.1 on 2025-06-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_service_options_alter_service_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Название вашего клуба', max_length=200, verbose_name='Название сайта (в Title)')),
                ('motto', models.CharField(blank=True, max_length=255, verbose_name='Девиз компании')),
                ('about_us_text', models.TextField(blank=True, verbose_name="Текст 'О нас'")),
            ],
            options={
                'verbose_name': 'Профиль компании и настройки сайта',
                'verbose_name_plural': 'Профили компании и настройки сайта',
            },
        ),
    ]