# Generated by Django 5.2.1 on 2025-06-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrbibolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_info', models.TextField(verbose_name="Общая информация (первый абзац под заголовком 'Орбибол')")),
                ('plot_title', models.CharField(default='Сюжетный орбибол', max_length=100, verbose_name="Заголовок блока 'Сюжетный'")),
                ('plot_description', models.TextField(verbose_name="Описание для 'Сюжетный орбибол'")),
                ('tactical_title', models.CharField(default='Тактический орбибол', max_length=100, verbose_name="Заголовок блока 'Тактический'")),
                ('tactical_description', models.TextField(verbose_name="Описание для 'Тактический орбибол'")),
                ('details_link', models.URLField(blank=True, max_length=250, null=True, verbose_name="Ссылка 'Узнать подробнее'")),
            ],
            options={
                'verbose_name': 'Информация об Орбиболе',
                'verbose_name_plural': 'Информация об Орбиболе',
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Контактный Email'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный Телефон'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='telegram_profile_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на профиль Telegram (для иконки в контактах)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vk_profile_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на профиль VK (для иконки в контактах)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='youtube_profile_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на профиль YouTube (для иконки в контактах)'),
        ),
    ]