# Generated by Django 5.2.1 on 2025-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_orbibolinfo_companyprofile_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок преимущества')),
                ('description', models.TextField(verbose_name='Описание преимущества')),
                ('icon', models.FileField(upload_to='feature_icons/', verbose_name='Иконка (SVG или PNG)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Преимущество (Что мы предлагаем)',
                'verbose_name_plural': 'Преимущества (Что мы предлагаем)',
                'ordering': ['order'],
            },
        ),
    ]
