# Generated by Django 5.2.1 on 2025-06-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа игры')),
                ('description', models.TextField(verbose_name='Краткое описание типа игры')),
                ('icon', models.FileField(upload_to='gametype_icons/', verbose_name='Иконка для типа игры (SVG или PNG)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': "Тип игры (секция 'Игры')",
                'verbose_name_plural': "Типы игр (секция 'Игры')",
                'ordering': ['order'],
            },
        ),
    ]