# Generated by Django 5.2.1 on 2025-06-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gametype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Игра/Услуга (для Записи на игру)', 'verbose_name_plural': 'Игры/Услуги (для Записи на игру)'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_description',
            field=models.TextField(default='Подробное описание скоро появится.', verbose_name='Подробное описание (Когда, Жанры, Цена и т.д.)'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_arts/', verbose_name='Арт для игры (для карусели)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Краткое описание/даты (для карусели)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название игры/услуги (для Записи на игру)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vk_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на VK для записи'),
        ),
    ]
