# Generated by Django 5.2.1 on 2025-06-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamond_count', models.PositiveIntegerField(default=8, verbose_name='Количество ромбиков')),
                ('diamond_size', models.PositiveIntegerField(default=12, verbose_name='Размер ромбика (в пикселях)')),
                ('active_color', models.CharField(default='#D90C6B', max_length=7, verbose_name='Цвет активного ромбика (HEX)')),
                ('inactive_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет неактивного ромбика (HEX)')),
            ],
            options={
                'verbose_name': 'Настройки пагинации карусели',
                'verbose_name_plural': 'Настройки пагинации карусели',
            },
        ),
    ]