# Generated by Django 5.2.1 on 2025-06-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_paginationsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaginationSettings',
        ),
        migrations.AddField(
            model_name='orbibolinfo',
            name='plot_icon',
            field=models.FileField(blank=True, null=True, upload_to='orbibol_icons/', verbose_name='Иконка для "Сюжетный орбибол" (SVG/PNG)'),
        ),
        migrations.AddField(
            model_name='orbibolinfo',
            name='tactical_icon',
            field=models.FileField(blank=True, null=True, upload_to='orbibol_icons/', verbose_name='Иконка для "Тактический орбибол" (SVG/PNG)'),
        ),
    ]
