# Generated by Django 5.2.1 on 2025-06-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_paginationsettings_orbibolinfo_plot_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to='site_assets/', verbose_name='Логотип сайта (SVG/PNG)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='telegram_icon',
            field=models.FileField(blank=True, null=True, upload_to='site_assets/', verbose_name='Иконка Telegram (SVG/PNG)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='vk_icon',
            field=models.FileField(blank=True, null=True, upload_to='site_assets/', verbose_name='Иконка VK (SVG/PNG)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='youtube_icon',
            field=models.FileField(blank=True, null=True, upload_to='site_assets/', verbose_name='Иконка YouTube (SVG/PNG)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='telegram_profile_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на профиль Telegram'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='vk_profile_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на профиль VK'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='youtube_profile_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка на профиль YouTube'),
        ),
    ]
