# Generated by Django 5.2.1 on 2025-06-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_companyprofile_logo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Краткое описание товара')),
                ('image', models.FileField(upload_to='product_images/', verbose_name='Изображение товара (SVG/PNG)')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на страницу товара')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='market_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Ссылка "Еще больше товаров" в Маркете'),
        ),
    ]
