# Generated by Django 5.2.1 on 2025-06-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_companyprofile_market_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок (напр. Фотосъемка)')),
                ('image', models.FileField(blank=True, help_text='Загрузите, если это фото.', null=True, upload_to='gallery/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, help_text='Загрузите, если это видео.', null=True, upload_to='gallery/', verbose_name='Видео (mp4, webm)')),
                ('order_link', models.URLField(verbose_name='Ссылка для кнопки "Заказать"')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Элемент галереи',
                'verbose_name_plural': 'Элементы галереи',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='gallery_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание для секции "Фото и видео галерея"'),
        ),
    ]
