# Generated by Django 5.2.1 on 2025-06-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_galleryitem_companyprofile_gallery_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='nav_toggle_icon',
            field=models.FileField(blank=True, null=True, upload_to='site_assets/', verbose_name='Иконка для раскрытия меню (в свернутом хедере)'),
        ),
    ]
