# Generated by Django 5.2.1 on 2025-06-21 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_companyprofile_nav_toggle_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Основные настройки фона', max_length=100, verbose_name='Название набора настроек')),
                ('background_pattern', models.FileField(blank=True, help_text='Это изображение будет повторяться на фоне.', null=True, upload_to='backgrounds/', verbose_name='Паттерн фона (повторяющееся изображение)')),
                ('pattern_size', models.CharField(default='200px', help_text="CSS значение, например: '200px', '50%', 'cover', 'contain'.", max_length=50, verbose_name='Размер паттерна')),
                ('pattern_opacity', models.DecimalField(decimal_places=2, default=0.1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Прозрачность паттерна (от 0.0 до 1.0)')),
                ('background_color', models.CharField(default='rgba(0,0,0,0.5)', help_text="CSS цвет, например: '#000000', 'rgba(0,0,0,0.5)'. Будет поверх паттерна.", max_length=20, verbose_name='Цвет-наложение на фон')),
            ],
            options={
                'verbose_name': 'Настройки фона',
                'verbose_name_plural': 'Настройки фона',
            },
        ),
        migrations.CreateModel(
            name='BackgroundObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название объекта')),
                ('image', models.FileField(upload_to='backgrounds/objects/', verbose_name='Изображение объекта')),
                ('width', models.PositiveIntegerField(default=150, verbose_name='Ширина объекта (px)')),
                ('initial_top', models.CharField(default='50%', help_text="CSS значение, например '50%' или '100px'", max_length=10, verbose_name='Начальная позиция сверху')),
                ('initial_left', models.CharField(default='50%', help_text="CSS значение, например '50%' или '100px'", max_length=10, verbose_name='Начальная позиция слева')),
                ('animation_duration', models.PositiveIntegerField(default=20, verbose_name='Длительность анимации (секунд)')),
                ('animation_delay', models.PositiveIntegerField(default=0, verbose_name='Задержка перед началом анимации (секунд)')),
                ('opacity', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Прозрачность (от 0.0 до 1.0)')),
                ('z_index', models.IntegerField(default=-9, help_text="Чем меньше, тем 'ниже' объект. Паттерн фона на слое -10.", verbose_name='Слой (z-index)')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='main.backgroundsettings', verbose_name='Набор настроек')),
            ],
            options={
                'verbose_name': 'Анимированный объект фона',
                'verbose_name_plural': 'Анимированные объекты фона',
                'ordering': ['order'],
            },
        ),
    ]
