# Generated by Django 5.2.1 on 2025-06-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_backgroundsettings_backgroundobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundobject',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_objects', to='main.backgroundsettings', verbose_name='Набор настроек'),
        ),
    ]
