# Generated by Django 5.2.1 on 2025-06-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_backgroundobject_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsettings',
            name='pattern_animation_duration',
            field=models.PositiveIntegerField(default=60, help_text="Время полного цикла 'плавания' фона. 0, чтобы отключить.", verbose_name='Длительность анимации паттерна (секунд)'),
        ),
    ]
