# Generated by Django 5.2.1 on 2025-06-21 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_backgroundsettings_pattern_animation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsettings',
            name='spotlight_enabled',
            field=models.BooleanField(default=True, verbose_name="Включить эффект 'прожектора'"),
        ),
        migrations.AddField(
            model_name='backgroundsettings',
            name='spotlight_size',
            field=models.PositiveIntegerField(default=500, verbose_name='Размер прожектора (px)'),
        ),
        migrations.AlterField(
            model_name='backgroundsettings',
            name='background_color',
            field=models.CharField(default='rgba(1,1,1,0.9)', help_text="CSS цвет, например: '#010101', 'rgba(1,1,1,0.9)'. Будет затемнять паттерн.", max_length=20, verbose_name='Цвет-наложение на фон'),
        ),
        migrations.AlterField(
            model_name='backgroundsettings',
            name='pattern_opacity',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Прозрачность паттерна (от 0.0 до 1.0)'),
        ),
    ]
