# Generated by Django 5.2.1 on 2025-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_backgroundsettings_spotlight_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundsettings',
            name='pattern_animation_duration',
        ),
        migrations.RemoveField(
            model_name='backgroundsettings',
            name='spotlight_enabled',
        ),
        migrations.RemoveField(
            model_name='backgroundsettings',
            name='spotlight_size',
        ),
        migrations.AlterField(
            model_name='backgroundsettings',
            name='background_color',
            field=models.CharField(default='#010101', help_text="CSS цвет, например: '#010101'. Будет под паттерном.", max_length=20, verbose_name='Основной цвет фона'),
        ),
    ]
