# Generated by Django 5.2.1 on 2025-06-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_backgroundsettings_pattern_animation_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundobject',
            name='parallax_speed',
            field=models.FloatField(default=0.3, help_text='Например: 0.2 (медленнее скролла), 1 (вместе со скроллом), -0.5 (в обратную сторону)', verbose_name='Скорость параллакса'),
        ),
        migrations.AddField(
            model_name='backgroundobject',
            name='parallax_target_id',
            field=models.CharField(blank=True, help_text="Например: 'about-us-section'. Оставьте пустым, чтобы отключить параллакс.", max_length=100, null=True, verbose_name='ID секции для параллакс-эффекта'),
        ),
        migrations.AlterField(
            model_name='backgroundobject',
            name='animation_duration',
            field=models.PositiveIntegerField(default=20, help_text="Длительность 'покачивания'. 0 чтобы отключить.", verbose_name='Длительность анимации (секунд)'),
        ),
    ]
