# Generated by Django 5.2.1 on 2025-06-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_backgroundobject_parallax_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hover_text',
            field=models.TextField(blank=True, help_text='Этот текст появится при наведении на центральный слайд. Если пусто, останется краткое описание.', null=True, verbose_name='Текст при наведении (в карусели)'),
        ),
    ]
