# START OF FILE: main/migrations/0023_companyprofile_favicon.py
# Generated by Django 5.2.1 on 2025-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_companyprofile_logo_image_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='favicon',
            field=models.FileField(blank=True, help_text='Иконка для вкладки браузера (файл .ico, .png или .svg)', null=True, upload_to='site_assets/', verbose_name='Фавикон'),
        ),
    ]
# END OF FILE: main/migrations/0023_companyprofile_favicon.py