# Generated by Django 5.2.1 on 2025-07-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_companyprofile_favicon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
