# Generated by Django 5.2.1 on 2025-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название игры/услуги')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (под названием)')),
                ('image', models.FileField(upload_to='service_images/', verbose_name='Изображение (для карточки в карусели)')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на VK для записи')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Игра/Услуга для карусели',
                'verbose_name_plural': 'Игры/Услуги для карусели',
                'ordering': ['order'],
            },
        ),
    ]
