# Generated by Django 5.2.1 on 2025-07-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
