# Generated by Django 5.2.1 on 2025-07-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about_us', 'О нас'), ('features', 'Что мы предлагаем (Преимущества)'), ('orbibol', 'Орбибол'), ('games', 'Игры'), ('market', 'Маркет'), ('gallery', 'Фото и видео галерея'), ('contacts', 'Контакты')], max_length=50, unique=True, verbose_name='Тип секции')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Включена')),
            ],
            options={
                'verbose_name': 'Секция на главной странице',
                'verbose_name_plural': 'Секции на главной странице',
                'ordering': ['order'],
            },
        ),
    ]
