# Generated by Django 5.2.1 on 2025-07-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='show_title',
            field=models.BooleanField(default=True, verbose_name='Показывать заголовок'),
        ),
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать заголовок по умолчанию.', max_length=200, verbose_name='Заголовок секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Секция включена'),
        ),
    ]
