# Generated by Django 5.2.1 on 2025-07-14 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_section_show_title_section_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundsettings',
            options={'verbose_name': '3. Настройки фона', 'verbose_name_plural': '3. Настройки фона'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': '1. Настройки главной страницы', 'verbose_name_plural': '1. Настройки главной страницы'},
        ),
        migrations.AlterModelOptions(
            name='orbibolinfo',
            options={'verbose_name': "2. Настройки секции 'Орбибол'", 'verbose_name_plural': "2. Настройки секции 'Орбибол'"},
        ),
        migrations.AddField(
            model_name='feature',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.companyprofile'),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='main.companyprofile'),
        ),
        migrations.AddField(
            model_name='gametype',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_types', to='main.companyprofile'),
        ),
        migrations.AddField(
            model_name='product',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.companyprofile'),
        ),
        migrations.AddField(
            model_name='section',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.companyprofile'),
        ),
    ]
