# Generated by Django 5.2.1 on 2025-07-15 14:00
# Этот файл создан вручную для переноса существующих данных.

from django.db import migrations

def link_data_to_profile(apps, schema_editor):
    """
    Эта функция привязывает все существующие записи в моделях
    к первому (и единственному) объекту CompanyProfile.
    """
    # Получаем актуальные версии моделей на момент этой миграции
    CompanyProfile = apps.get_model('main', 'CompanyProfile')
    Feature = apps.get_model('main', 'Feature')
    GameType = apps.get_model('main', 'GameType')
    Product = apps.get_model('main', 'Product')
    GalleryItem = apps.get_model('main', 'GalleryItem')
    Section = apps.get_model('main', 'Section')

    # Находим первый (и единственный) профиль компании.
    # Если его нет (например, при самой первой установке), то ничего не делаем.
    try:
        profile = CompanyProfile.objects.first()
    except CompanyProfile.DoesNotExist:
        profile = None

    if profile:
        # Для каждой модели, находим все записи, где company_profile еще не установлен (is null)
        # и обновляем их, устанавливая ссылку на найденный профиль.
        Feature.objects.filter(company_profile__isnull=True).update(company_profile=profile)
        GameType.objects.filter(company_profile__isnull=True).update(company_profile=profile)
        Product.objects.filter(company_profile__isnull=True).update(company_profile=profile)
        GalleryItem.objects.filter(company_profile__isnull=True).update(company_profile=profile)
        Section.objects.filter(company_profile__isnull=True).update(company_profile=profile)

def reverse_code(apps, schema_editor):
    """
    Функция для отката миграции. 
    Мы намеренно ничего не делаем, так как отвязывать данные обратно не требуется.
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
       
        ('main', '0029_alter_backgroundsettings_options_and_more'), 
    ]

    operations = [
        migrations.RunPython(link_data_to_profile, reverse_code=reverse_code),
    ]