# Generated by Django 5.2.1 on 2025-07-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_link_existing_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='company_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.companyprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='company_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='main.companyprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gametype',
            name='company_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_types', to='main.companyprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='company_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.companyprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='company_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.companyprofile'),
            preserve_default=False,
        ),
    ]
