# Generated by Django 5.2.1 on 2025-07-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_feature_company_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': '1. Главные настройки сайта', 'verbose_name_plural': '1. Главные настройки сайта'},
        ),
        migrations.AddField(
            model_name='orbibolinfo',
            name='company_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orbibol_info', to='main.companyprofile'),
        ),
    ]
