# Generated by Django 5.2.1 on 2025-07-14 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_link_orbibol_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbibolinfo',
            name='company_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orbibol_info', to='main.companyprofile'),
            preserve_default=False,
        ),
    ]
