# Generated by Django 5.2.1 on 2025-07-14 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_orbibolinfo_company_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orbibolinfo',
            options={'verbose_name': "Настройки секции 'Орбибол'", 'verbose_name_plural': "Настройки секции 'Орбибол'"},
        ),
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('about_us', 'О нас'), ('features', 'Что мы предлагаем (Преимущества)'), ('carousel', 'Карусель'), ('orbibol', 'Орбибол'), ('games', 'Игры'), ('market', 'Маркет'), ('gallery', 'Фото и видео галерея'), ('contacts', 'Контакты')], max_length=50, unique=True, verbose_name='Тип секции'),
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название/Заголовок слайда')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание (под названием)')),
                ('image', models.FileField(upload_to='carousel_slides/', verbose_name='Изображение для слайда')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='Ссылка для кнопки')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('company_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_slides', to='main.companyprofile')),
            ],
            options={
                'verbose_name': 'Слайд для карусели',
                'verbose_name_plural': 'Слайды для карусели',
                'ordering': ['order'],
            },
        ),
    ]
