# Generated by Django 5.2.1 on 2025-07-15... (дата будет ваша)

from django.db import migrations

def create_initial_sections(apps, schema_editor):
    """
    Создает все недостающие секции для существующего профиля компании.
    Это гарантирует, что все типы секций, включая 'Карусель', существуют в БД.
    """
    CompanyProfile = apps.get_model('main', 'CompanyProfile')
    Section = apps.get_model('main', 'Section')

    # Проверяем, существует ли хотя бы один профиль
    profile = CompanyProfile.objects.first()
    if not profile:
        return # Если профиля нет, ничего не делаем

    # Проходим по всем возможным типам секций из модели
    for index, (section_type, display_name) in enumerate(Section.SECTION_CHOICES):
        # Используем get_or_create, чтобы создать секцию, только если ее нет
        # Это безопасно для повторного запуска
        obj, created = Section.objects.get_or_create(
            company_profile=profile,
            section_type=section_type,
            # defaults - это значения, которые будут установлены только при создании новой записи
            defaults={
                'title': display_name,
                'order': index
            }
        )
        if created:
            print(f"Создана недостающая секция: {display_name}")

class Migration(migrations.Migration):

    dependencies = [
        # Указываем зависимость от предыдущей миграции
        ('main', '0035_alter_orbibolinfo_options_alter_section_section_type_and_more'),
    ]

    operations = [
        # Запускаем наш Python-скрипт для "лечения" базы
        migrations.RunPython(create_initial_sections, reverse_code=migrations.RunPython.noop),
    ]