# Generated by Django 5.2.1 on 2025-07-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_create_all_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselslide',
            name='short_description',
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='date_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дата/Подзаголовок (виден всегда)'),
        ),
        migrations.AddField(
            model_name='carouselslide',
            name='hover_description',
            field=models.TextField(blank=True, verbose_name='Описание (появляется при наведении)'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название/Заголовок слайда (виден всегда)'),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='vk_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка для кнопки (весь слайд)'),
        ),
    ]
