# Generated by Django 5.2.1 on 2025-07-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_carouselslide_short_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryitem',
            name='order_link',
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='title',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='gallery_button_link',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name="Ссылка для кнопки 'Узнать подробнее' в галерее"),
        ),
    ]
