# Generated by Django 5.2.1 on 2025-07-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_galleryitem_order_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='gallery_button_text',
            field=models.CharField(blank=True, default='Узнать подробнее', max_length=100, verbose_name='Текст для кнопки в галерее'),
        ),
    ]
