# Generated by Django 5.2.1 on 2025-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_companyprofile_gallery_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='body_font',
            field=models.CharField(choices=[('SUNDAY', 'Sunday (кастомный, для заголовков)'), ('FortuneC', 'FortuneC (кастомный, для текста)'), ('Montserrat', 'Montserrat (современный, гротеск)'), ('Roboto', 'Roboto (классический, без засечек)'), ('Playfair Display', 'Playfair Display (элегантный, с засечками)'), ('Lobster', 'Lobster (рукописный, акцентный)')], default='FortuneC', max_length=100, verbose_name='Шрифт для основного текста (параграфы)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='header_font',
            field=models.CharField(choices=[('SUNDAY', 'Sunday (кастомный, для заголовков)'), ('FortuneC', 'FortuneC (кастомный, для текста)'), ('Montserrat', 'Montserrat (современный, гротеск)'), ('Roboto', 'Roboto (классический, без засечек)'), ('Playfair Display', 'Playfair Display (элегантный, с засечками)'), ('Lobster', 'Lobster (рукописный, акцентный)')], default='SUNDAY', max_length=100, verbose_name='Шрифт для заголовков (H1, H2 и т.д.)'),
        ),
    ]
