# Generated by Django 5.2.1 on 2025-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_customfont_font_file_otf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('about_us', 'О нас'), ('features', 'Что мы предлагаем (Преимущества)'), ('carousel', 'Карусель'), ('orbibol', 'Орбибол'), ('games', 'Игры'), ('market', 'Маркет'), ('gallery', 'Фото и видео галерея'), ('contacts', 'Контакты')], max_length=50, verbose_name='Тип секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок секции'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('company_profile', 'section_type')},
        ),
    ]
