# Generated by Django 5.2.1 on 2025-07-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_section_section_type_alter_section_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать заголовок по умолчанию.', max_length=200, verbose_name='Заголовок секции'),
        ),
    ]
