# Generated by Django 5.2.1 on 2025-07-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_companyprofile_body_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='market_button_text',
            field=models.CharField(blank=True, default='Еще больше товаров в нашем маркете', max_length=100, verbose_name="Текст для ссылки 'Еще больше товаров' (Маркет)"),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='orbibol_details_button_text',
            field=models.CharField(blank=True, default='Узнать подробнее', max_length=100, verbose_name="Текст для кнопки 'Узнать подробнее' (Орбибол)"),
        ),
    ]
