# Generated by Django 5.2.1 on 2025-07-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_companyprofile_market_button_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='Основной заголовок страницы для поисковых систем (до 60 символов).', max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Краткое описание страницы для поисковых систем (до 160 символов).', max_length=300, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую. Этот тег почти не используется современными поисковиками, но может быть полезен.', max_length=255, verbose_name='Meta Keywords')),
                ('og_title', models.CharField(blank=True, help_text='Заголовок, который будет виден при репосте ссылки в соцсети.', max_length=200, verbose_name='Open Graph Title')),
                ('og_description', models.TextField(blank=True, help_text='Описание для репоста в соцсети.', max_length=300, verbose_name='Open Graph Description')),
                ('og_image', models.ImageField(blank=True, help_text='Картинка для репоста (рекомендуемый размер 1200x630px).', null=True, upload_to='seo_images/', verbose_name='Open Graph Image')),
                ('json_ld_schema', models.TextField(blank=True, default='{\n  "@context": "https://schema.org",\n  "@type": "SportsClub",\n  "name": "Название Вашего Клуба",\n  "alternateName": "Maybe",\n  "description": "Клуб активного отдыха...",\n  "url": "https://maybe-7u6w.onrender.com/",\n  "logo": "URL вашего логотипа",\n  "address": {\n    "@type": "PostalAddress",\n    "streetAddress": "Ваша улица и дом",\n    "addressLocality": "Ваш город",\n    "postalCode": "Ваш индекс",\n    "addressCountry": "RU"\n  },\n  "contactPoint": {\n    "@type": "ContactPoint",\n    "telephone": "+7-XXX-XXX-XX-XX",\n    "contactType": "customer service"\n  }\n}', help_text='Сюда вставляется код разметки Schema.org в формате JSON-LD. Например, для организации или мероприятия.', verbose_name='Структурированные данные (JSON-LD)')),
                ('company_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_settings', to='main.companyprofile', verbose_name='Профиль компании')),
            ],
            options={
                'verbose_name': '2. Настройки SEO',
                'verbose_name_plural': '2. Настройки SEO',
            },
        ),
    ]
