# Generated by Django 5.2.1 on 2025-07-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_seosettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='mobile_menu_indicator_icon',
            field=models.FileField(blank=True, null=True, upload_to='site_assets/', verbose_name='Иконка-индикатор для моб. меню (стрелка вниз)'),
        ),
    ]
