# Generated by Django 5.2.1 on 2025-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_companyprofile_mobile_menu_indicator_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='button_text',
            field=models.CharField(default='Заказать игру', max_length=100, verbose_name='Текст кнопки'),
        ),
    ]
