# Generated by Django 5.2.1 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_product_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='section_vertical_padding',
            field=models.PositiveIntegerField(default=5, help_text="Укажите число. Значение будет использовано в 'rem' (например, 5 = 5rem). 1rem ~ 16px.", verbose_name='Вертикальный отступ секций (верх/низ)'),
        ),
    ]
